root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main ./cmd"
  bin = "tmp/main"
  exclude_dir = ["tmp", "vendor", "node_modules"]
  include_ext = ["go", "tpl", "tmpl", "html"]

[log]
  level = "debug"
