apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: gitops-lab
servers: 1
agents: 1
ports:
  - port: "18080:80"
options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
