services:
  db:
    container_name: semantra-db
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: semantra
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    volumes:
      - ../db/pgdata:/var/lib/postgresql/data
    networks:
      - semantra_net
  api:
    container_name: semantra-api
    build:
      context: ../api
      dockerfile: Dockerfile.dev
    working_dir: /app
    environment:
      CONFIG_FILE_PATH: "/app/config.dev.json"
      SERVER_PORT: "8081"
    volumes:
      - ../api:/app
    ports:
      - "8081:8081"
    networks:
      - semantra_net
    depends_on:
      - db

  bff:
    build:
      context: ../bff
    ports:
      - "4000:4000"
    networks:
      - semantra_net
    depends_on:
      - api

  web:
    container_name: semantra-web
    build:
      context: ../web
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - ../web/src:/app/src
      - ../web/public:/app/public
      - ../web/tsconfig.json:/app/tsconfig.json
      - ../web/next.config.ts:/app/next.config.ts
    ports:
      - "3001:3000"
    networks:
      - semantra_net
    depends_on:
      - api
  es:
    container_name: semantra-es
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2-arm64
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - semantra_net

  gate:
    container_name: semantra-gate
    image: kong:3.3
    ports:
      - "8001:8001"
      - "8002:8002" # Admin API (optional)
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
    volumes:
      - ../gate/kong.yml:/etc/kong/kong.yml
    networks:
      - semantra_net

networks:
  semantra_net:
    driver: bridge
